webapp/forms/ArticleForm.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, TextAreaField, FileField
from wtforms.validators import DataRequired


class ArticleForm(FlaskForm):
    article_title = StringField("Название статьи", validators=[DataRequired(message='Поле "Название" обязательно для '
                                                                                    'заполнения')])
    article_text = TextAreaField("Текст статьи", validators=[DataRequired(message='Поле "Текст" обязательно для '
                                                                                  'заполнения')])
    cover_image = FileField("Прикрепите изображение", validators=[FileAllowed(
        ['jpg', 'jpeg', 'png'], 'Загружать можно только изображения формата "jpg", "jpeg", "png" !')])

webapp/forms/CourseForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired


class CourseForm(FlaskForm):
    course_title = StringField("Название курса", validators=[DataRequired(message='Поле "Название" обязательно для '
                                                                                  'заполнения')])
    description = TextAreaField("Описание курса", validators=[DataRequired(message='Поле "Описание" обязательно для '
                                                                                   'заполнения')])

webapp/forms/DeleteArticleForm.py
from flask_wtf import FlaskForm
from wtforms import BooleanField


class DeleteArticleForm(FlaskForm):
    user_agreement = BooleanField("Удалить статью")

    def __init__(self, *args, custom_label=None, **kwargs):
        super(DeleteArticleForm, self).__init__(*args, **kwargs)
        if custom_label:
            self.user_agreement.label.text = f"Я подтверждаю, что хочу удалить статью {custom_label}"

webapp/forms/DeleteCourseForm.py
from flask_wtf import FlaskForm
from wtforms import BooleanField


class DeleteCourseForm(FlaskForm):
    user_agreement = BooleanField("Удалить курс")

    def __init__(self, *args, custom_label=None, **kwargs):
        super(DeleteCourseForm, self).__init__(*args, **kwargs)
        if custom_label:
            self.user_agreement.label.text = f"Я подтверждаю, что хочу удалить курс {custom_label}"

webapp/forms/LoginForm.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, EmailField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    email = EmailField("Email", validators=[DataRequired(message='Поле "Email" обязательно для заполнения')])
    password = PasswordField("Пароль", validators=[DataRequired(message='Поле "Пароль" обязательно для заполнения')])

webapp/forms/RegistrationForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, PasswordField
from wtforms.validators import DataRequired, ValidationError


class RegistrationForm(FlaskForm):
    login = StringField("Имя пользователя", validators=[DataRequired(message='Поле "Имя" обязательно для заполнения')])
    email = EmailField("Email", validators=[DataRequired(message='Поле "Email" обязательно для заполнения')])
    password = PasswordField("Пароль", validators=[DataRequired(message='Поле "Пароль" обязательно для заполнения')])
    password_repeat = PasswordField("Повторите пароль", validators=[DataRequired(message='Поле "Повторите пароль" '
                                                                                         'обязательно для заполнения')])

    def validate_password_repeat(self, field):
        if field.data != self.password.data:
            raise ValidationError("Пароли должны совпадать!")

webapp/routes/accounting.py
from functools import partial

from flask import Blueprint, redirect, url_for, session, abort, request, render_template, flash
from flask_login import login_required, logout_user, current_user, login_user

import webapp.db.accounting_functions as db_ac
import webapp.db.courses_functions as db_crs
from exceptions import exceptions
from forms.LoginForm import LoginForm
from forms.RegistrationForm import RegistrationForm
from pagination.Paginator import Paginator

accounting_bp = Blueprint("accounting", __name__)


@accounting_bp.route("/logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    session.clear()
    return redirect(url_for("courses.show_courses"))


@accounting_bp.route("/login", methods=("GET", "POST"))
def login():
    if current_user.is_authenticated:
        abort(404)
    form = LoginForm()
    _render_template = partial(render_template, "login.html", form=form)
    if request.method == "GET":
        return _render_template()
    if not form.validate_on_submit():
        errors = [error for errors in form.errors.values() for error in errors]
        for error in errors:
            flash(error)
        return _render_template()
    user = db_ac.find_user_by_email(form.email.data)
    if user is not None and user.check_password(form.password.data):
        login_user(user)
        session.permanent = True
        return redirect(url_for("courses.show_courses"))
    flash("Неверная информация в полях авторизации")
    return _render_template()


@accounting_bp.route("/registration", methods=("GET", "POST"))
def registration():
    if current_user.is_authenticated:
        abort(404)
    form = RegistrationForm()
    _render_template = partial(render_template, "registration.html", form=form)
    if request.method == "GET":
        return _render_template()
    if not form.validate_on_submit():
        errors = [error for errors in form.errors.values() for error in errors]
        for error in errors:
            flash(error)
        return _render_template()
    try:
        db_ac.register_user(form.login.data, form.email.data, form.password.data)
    except exceptions.AlreadyRegisteredException:
        flash("Пользователь с таким логином или email уже зарегистрирован!")
        return _render_template()
    user = db_ac.find_user_by_login(form.login.data)
    login_user(user)
    return redirect(url_for("courses.show_courses"))


@accounting_bp.route("/profile", methods=["GET"])
@login_required
def show_profile():
    courses_per_page = 6
    page = request.args.get('page', default=1, type=int)
    courses_paginator = Paginator(page, courses_per_page, db_crs.get_count_of_fav_courses())
    offset = (page - 1) * courses_per_page
    fav_courses = db_crs.get_fav_courses_per_page(current_user.user_id, courses_per_page, offset)
    user_comments = db_crs.get_comments_left_by_user(current_user)
    return render_template("user_profile.html", fav_courses=fav_courses, page=page, comments=user_comments,
                           paginator=courses_paginator)


@accounting_bp.route("/admin_panel", methods=["GET"])
@login_required
def show_admin_panel():
    if current_user.role != 'admin':
        abort(404)
    users = db_ac.get_all_users()
    return render_template("admin_panel.html", users=users)


@accounting_bp.route("/admin_panel/<string:user_id>/to_author", methods=["GET"])
@login_required
def make_author_from_reader(user_id: str):
    if current_user.role != 'admin':
        abort(404)
    user = db_ac.find_user_by_id(user_id)
    users = db_ac.get_all_users()
    if user is None or user not in users:
        abort(404)
    db_ac.user_to_author(user_id)
    return redirect(url_for(".show_admin_panel"))


@accounting_bp.route("/admin_panel/<string:user_id>/to_reader", methods=["GET"])
@login_required
def make_reader_from_author(user_id: str):
    if current_user.role != 'admin':
        abort(404)
    user = db_ac.find_user_by_id(user_id)
    users = db_ac.get_all_users()
    if user is None or user not in users:
        abort(404)
    db_ac.user_to_reader(user_id)
    return redirect(url_for(".show_admin_panel"))

webapp/routes/courses.py
from functools import partial

from flask import Blueprint, request, render_template, abort, flash, redirect, url_for
from flask_login import current_user, login_required

import webapp.db.courses_functions as db_crs
from exceptions import exceptions
from forms.ArticleForm import ArticleForm
from forms.CommentsForm import CommentsForm
from forms.CourseForm import CourseForm
import webapp.images.image_functions as img_funcs
from forms.DeleteArticleForm import DeleteArticleForm
from forms.DeleteCourseForm import DeleteCourseForm
from webapp.pagination.Paginator import Paginator

courses_bp = Blueprint("courses", __name__)


@courses_bp.route("/", methods=["GET"])
def show_courses():
    courses_per_page = 6
    page = request.args.get('page', default=1, type=int)
    title_to_find = request.args.get('title', default="", type=str)
    description_to_find = request.args.get('description', default="", type=str)
    courses_paginator = Paginator(page, courses_per_page, db_crs.get_count_of_courses(title_to_find,
                                                                                      description_to_find))
    offset = (page - 1) * courses_per_page
    if current_user.is_authenticated:
        courses_on_this_page = db_crs.get_courses_per_page(current_user.user_id, courses_per_page, offset,
                                                           title_to_find, description_to_find)
        fav_courses = db_crs.get_courses_favoured_by_user(current_user)
    else:
        courses_on_this_page = db_crs.get_courses_per_page(None, courses_per_page, offset, title_to_find,
                                                           description_to_find)
        fav_courses = []
    fav_ids = {course.course_id for course in fav_courses}
    return render_template("index.html", courses=courses_on_this_page, page=page, paginator=courses_paginator,
                           fav_ids=fav_ids, title_to_find=title_to_find, description_to_find=description_to_find)


@courses_bp.route("/<string:course_id>", methods=["GET"])
@login_required
def show_course_page(course_id: str):
    articles_per_page = 3
    page = request.args.get('page', default=1, type=int)
    course = db_crs.find_course_by_id(course_id)
    if course is None:
        abort(404)
    articles_paginator = Paginator(page, articles_per_page, db_crs.get_count_of_articles_in_course(course_id))
    offset = (page - 1) * articles_per_page
    articles = db_crs.get_all_articles_at_course(course_id, articles_per_page, offset)
    images = [img_funcs.dump_image(article.image) for article in articles]
    return render_template("course.html", course=course, articles=articles, images=images, page=page,
                           paginator=articles_paginator)


@courses_bp.route("/new", methods=("GET", "POST"))
@login_required
def create_course():
    if current_user.role != 'author':
        abort(404)
    form = CourseForm()
    _render_template = partial(render_template, "new_course.html", form=form)
    if request.method == "GET":
        return _render_template()
    if not form.validate_on_submit():
        errors = [error for errors in form.errors.values() for error in errors]
        for error in errors:
            flash(error)
        return _render_template()
    try:
        db_crs.add_course(form.course_title.data, current_user, form.description.data)
    except exceptions.CourseAlreadyExists:
        flash("Курс с таким названием уже существует")
        return _render_template()
    return redirect(url_for(".show_courses"))


@courses_bp.route("/<string:course_id>/to_favourite", methods=["GET"])
@login_required
def add_course_to_favourites(course_id: str):
    course = db_crs.find_course_by_id(course_id)
    if course is None:
        abort(404)
        db_crs.add_course_to_favourites(current_user, course_id)
        return redirect(url_for(".show_courses"))


@courses_bp.route("/<string:course_id>/out_of_favourite", methods=["GET"])
@login_required
def unfavourite_course(course_id: str):
    course = db_crs.find_course_by_id(course_id)
    if course is None:
        abort(404)
    db_crs.remove_course_from_favoured(current_user, course_id)
    return redirect(url_for(".show_courses"))


@courses_bp.route("/<string:course_id>/out_of_favourite_from_profile", methods=["GET"])
@login_required
def unfavourite_course_from_profile(course_id: str):
    course = db_crs.find_course_by_id(course_id)
    if course is None:
        abort(404)
    db_crs.remove_course_from_favoured(current_user, course_id)
    return redirect(url_for("accounting.show_profile"))


@courses_bp.route("/<string:course_id>/edit", methods=("GET", "POST"))
@login_required
def edit_course(course_id: str):
    course = db_crs.find_course_by_id(course_id)
    if course is None:
        abort(404)
    if not (course.author == current_user or current_user.role == 'admin'):
        abort(404)
    form = CourseForm()
    _render_template = partial(render_template, "edit_course.html", form=form)
    if request.method == "GET":
        form.course_title.data = course.course_title
        form.description.data = course.description
        return _render_template()
    form.course_title.data = request.form.get('course_title', '')
    form.description.data = request.form.get('description', '')
    if not form.validate_on_submit():
        errors = [error for errors in form.errors.values() for error in errors]
        for error in errors:
            flash(error)
        return _render_template()
    try:
        db_crs.edit_course(form.course_title.data, form.description.data, course_id)
    except exceptions.CourseAlreadyExists:
        flash("Курс с таким названием уже существует")
        return _render_template()
    return redirect(url_for(".show_courses"))


@courses_bp.route("/<string:course_id>/delete", methods=("GET", "POST"))
@login_required
def delete_course(course_id: str):
    course = db_crs.find_course_by_id(course_id)
    if course is None:
        abort(404)
    if not (course.author == current_user or current_user.role == 'admin'):
        abort(404)
    form = DeleteCourseForm(custom_label=course.course_title)
    articles_count = db_crs.get_count_of_articles_in_course(course_id)
    _render_template = partial(render_template, "delete_course.html", form=form, course=course,
                               articles_count=articles_count)
    if request.method == "GET":
        return _render_template()
    if form.validate_on_submit():
        if form.user_agreement.data:
            db_crs.delete_course(course_id)
            return redirect(url_for(".show_courses"))
        else:
            return _render_template(check=True)


@courses_bp.route("/<string:course_id>/articles/new", methods=("GET", "POST"))
@login_required
def create_article(course_id: str):
    course = db_crs.find_course_by_id(course_id)
    if course is None:
        abort(404)
    if current_user != course.author:
        abort(404)
    form = ArticleForm()
    _render_template = partial(render_template, "new_article.html", form=form)
    if request.method == "GET":
        return _render_template()
    if not form.validate_on_submit():
        errors = [error for errors in form.errors.values() for error in errors]
        for error in errors:
            flash(error)
        return _render_template()
    try:
        image = img_funcs.load_image(form.cover_image.data)
        db_crs.add_article(form.article_title.data, course_id, form.article_text.data, current_user, image)
    except exceptions.ArticleAlreadyExists:
        flash("Статья с таким названием уже существует в данном курсе")
        return _render_template()
    return redirect(url_for(".show_course_page", course_id=course_id))


@courses_bp.route("/<string:course_id>/articles/<string:article_id>", methods=["GET"])
@login_required
def show_article_page(course_id: str, article_id: str):
    course = db_crs.find_course_by_id(course_id)
    article = db_crs.find_article_by_id(article_id)
    if course is None or article is None:
        abort(404)
    form = CommentsForm()
    comments = db_crs.get_comments_for_article(article_id)
    comments_replies_dict = {comment: db_crs.get_replies_for_comment(comment.comment_id) for comment in comments}
    image = img_funcs.dump_image(article.image)
    return render_template("article.html", article=article, image=image, course=course, form=form,
                           comments_and_replies=comments_replies_dict)


@courses_bp.route("/<string:course_id>/articles/<string:article_id>/delete", methods=("GET", "POST"))
@login_required
def delete_article(course_id: str, article_id: str):
    course = db_crs.find_course_by_id(course_id)
    article = db_crs.find_article_by_id(article_id)
    if course is None or article is None:
        abort(404)
    if not (article.author == current_user or current_user.role == 'admin'):
        abort(404)
    form = DeleteArticleForm(custom_label=article.article_title)
    _render_template = partial(render_template, "delete_article.html", form=form, article=article, course=course)
    if request.method == "GET":
        return _render_template()
    if form.validate_on_submit():
        if form.user_agreement.data:
            db_crs.delete_article(article_id)
            return redirect(url_for(".show_course_page", course_id=course_id))
        else:
            return _render_template(check=True)


@courses_bp.route("/<string:course_id>/articles/<string:article_id>/edit", methods=("GET", "POST"))
@login_required
def edit_article(course_id: str, article_id: str):
    course = db_crs.find_course_by_id(course_id)
    article = db_crs.find_article_by_id(article_id)
    if course is None or article is None:
        abort(404)
    if not (article.author == current_user or current_user.role == 'admin'):
        abort(404)
    form = ArticleForm()
    _render_template = partial(render_template, "edit_article.html", form=form)

templates/article.html
{% extends "base.html" %}

{% block title %} {{ article.article_title }} {% endblock %}

{% block headExtraContent %}
<style>
        .cover-image {
            width: 50%;
            height: auto;
        }
        .article-title {
            font-size: 2em;
            font-weight: bold;
        }
        .author-name {
            font-style: italic;
            font-size: 1.2em;
        }
        .comments-section {
            margin-top: 30px;
        }

    .toast {
    background-color: #343a40;
    color: white;
  }

  .toast-header {
    background-color: #343a40;
    color: white;
  }

  .toast-body {
     border-top: 2px solid #000000;
    padding: 10px;
  }

  .btn-close {
    filter: brightness(0) invert(1);
  }

    </style>
{% endblock %}


{% block content %}

{% include 'navbar_template.html' %}


<div class="container mt-4">

    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <a class="nav-link active" id="article-tab" data-bs-toggle="tab" href="#article" role="tab" aria-controls="article" aria-selected="true">Статья</a>
        </li>
        <li class="nav-item" role="presentation">
            <a class="nav-link" id="comments-tab" data-bs-toggle="tab" href="#comments" role="tab" aria-controls="comments" aria-selected="false">Комментарии</a>
        </li>
    </ul>

    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="article" role="tabpanel" aria-labelledby="article-tab">

            <div class="d-flex justify-content-between align-items-center mt-3">
    <a href="{{ url_for('courses.show_course_page', course_id=course.course_id) }}" class="btn btn-secondary mb-3">
        <i class="bi bi-arrow-left-circle-fill"></i> Назад к курсу</a>

          {% if article.author == current_user or current_user.role == 'admin' %}
            <div class="btn-group">
            <a href="{{ url_for('courses.edit_article',course_id=course.course_id, article_id=article.article_id) }}" class="btn btn-sm btn-outline-secondary" role="button">
                <i class="bi bi-pencil"></i></a>
            <a href="{{ url_for('courses.delete_article', course_id=course.course_id, article_id=article.article_id) }}" class="btn btn-sm btn-outline-secondary" role="button">
            <i class="bi bi-trash"></i></a>
            </div>
              {% endif %}
        </div>

            <div class="mt-3 text-center">
                {% if image is none %}
                    <img src="{{ url_for('static', filename='img/no_image.jpg') }}" class="cover-image" alt="Заглушка обложки">
                {% else %}
                    <img src="data:image/png;base64,{{ image|safe }}" alt="Обложка статьи" class="cover-image">
                {% endif %}
            </div>
            <div class="mt-3">
                <h1 class="article-title mt-3"> {{ article.article_title }} </h1>
                <p class="author-name">Автор: {{ article.author.login }}</p>

                {% for par in article.article_text.splitlines() %}
                    <p> {{ par|trim }} </p>
                {% endfor %}
            </div>
        </div>

        <div class="tab-pane fade" id="comments" role="tabpanel" aria-labelledby="comments-tab">

            <div class="mt-3">
                 <a href="{{ url_for('courses.show_course_page', course_id=course.course_id) }}" class="btn btn-secondary mb-3">
        <i class="bi bi-arrow-left-circle-fill"></i> Назад к курсу</a>
            </div>

            <div class="comments-section">
                <h3>Комментарии</h3>

                <form action="{{ url_for('courses.add_comment', article_id=article.article_id, course_id=course.course_id) }}" method="POST">
                    <div class="mb-3">
                        {{ form.csrf_token }}
                        {{ form.comment_text.label(class='form-label') }}
                        {{ form.comment_text(class='form-control', style='resize: none;', rows='3') }}
                    </div>
                    <button type="submit" class="btn btn-primary">Отправить</button>
                </form>

                <hr>
                <div class="comment-list">
                {% if comments_and_replies|length == 0 %}
                    <div class="container">
                            Пока что к статье нет ни одного комментария...
                     </div>
                {% else %}
                    {% for comment, replies in comments_and_replies.items() %}
                        <div class="comment-item">
                            <p style="display: inline-block;"><a name="comment-{{ comment.comment_id }}"></a><strong>{{ comment.author.login }}:</strong> {{ comment.comment_text}}</p>
                            {% if article.author == current_user or current_user.role == 'admin' %}
                                    <a href="{{ url_for('courses.delete_comment', course_id=course.course_id, article_id=article.article_id, comment_id=comment.comment_id) }}" class="btn btn-sm btn-outline-secondary" role="button" style="display: inline-block;">
                                                <i class="bi bi-trash"></i></a>
                            {% endif %}

                            {% if replies|length != 0 %}
                                {% for reply in replies %}
                            <div>
                                <p style="display: inline-block; margin-left: 30px;"><a name="comment-{{ reply.comment_id }}"></a><strong>{{ reply.author.login }}:</strong> {{ reply.comment_text}}</p>
                                 {% if article.author == current_user or current_user.role == 'admin' %}
                                        <a href="{{ url_for('courses.delete_comment', course_id=course.course_id, article_id=article.article_id, comment_id=reply.comment_id) }}" class="btn btn-sm btn-outline-secondary" role="button" style="display: inline-block;">
                                                    <i class="bi bi-trash"></i></a>
                                {% endif %}
                            </div>
                                {% endfor %}
                                    {% set last_reply = replies | last %}
                                    {% if current_user == article.author or current_user.role == 'admin' or current_user == comment.author  %}
                                        {% if not (last_reply.author.role == 'reader' and current_user.role == 'reader')  %}
                                            <form action="{{ url_for('courses.reply_to_comment', article_id=article.article_id, course_id=course.course_id, comment_id=comment.comment_id) }}"
                                                  method="POST" style="margin-left: 30px;">
                                                    <div class="mb-3">
                                                        {{ form.csrf_token }}
                                                        {{ form.comment_text(class='form-control', style='resize: none; width: 70%;', rows='2') }}
                                                    </div>
                                                    <button type="submit" class="btn btn-info" style="margin-bottom: 15px;">Ответить</button>
                                            </form>
                                        {% endif %}
                                    {% endif %}
                            {% else %}
                                {% if current_user == article.author or current_user.role == 'admin' %}
                                <form action="{{ url_for('courses.reply_to_comment', article_id=article.article_id, course_id=course.course_id, comment_id=comment.comment_id) }}"
                                                      method="POST" style="margin-left: 30px;">
                                                        <div class="mb-3">
                                                            {{ form.csrf_token }}
                                                            {{ form.comment_text(class='form-control', style='resize: none; width: 70%;', rows='2') }}
                                                        </div>
                                                        <button type="submit" class="btn btn-info" style="margin-bottom: 15px;">Ответить</button>
                                                </form>
                                {% endif %}
                            {% endif %}
                        </div>
                    {% endfor %}
                {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'errors_template.html' %}


<script>
    document.addEventListener('DOMContentLoaded', function() {
        const tabs = document.querySelectorAll('.nav-link');
        const storedTab = localStorage.getItem('activeTab'); // Получаем сохраненную вкладку

        // Функция для получения параметров URL
        function getParameterByName(name) {
            const urlParams = new URLSearchParams(window.location.search);
            return urlParams.get(name);
        }

        // Проверяем наличие параметра active_tab в URL
        const urlTab = getParameterByName('active_tab');

        // Определяем активную вкладку
        const activeTab = urlTab || storedTab || tabs[0].getAttribute('href'); // По умолчанию первая вкладка

        tabs.forEach(tab => {
            tab.classList.remove('active'); // Сбрасываем классы активности
            const target = document.querySelector(tab.getAttribute('href'));
            if (target) {
                target.classList.remove('show', 'active'); // Скрываем все содержимое вкладок
            }

            // Добавляем слушатель события для переключения вкладок
            tab.addEventListener('click', function(event) {
                event.preventDefault(); // Предотвращаем переход по ссылке
                const href = tab.getAttribute('href');
                localStorage.setItem('activeTab', href); // Сохраняем активную вкладку

                // Обновляем URL без перезагрузки страницы
                const url = new URL(window.location);
                url.searchParams.set('active_tab', href);
                window.history.pushState({}, '', url);

                // Активируем новую вкладку
                tabs.forEach(t => {
                    t.classList.remove('active'); // Сбрасываем классы активности
                    const target = document.querySelector(t.getAttribute('href'));
                    if (target) {
                        target.classList.remove('show', 'active'); // Скрываем все содержимое вкладок
                    }
                });

                // Активируем нужную вкладку
                tab.classList.add('active');
                document.querySelector(href).classList.add('show', 'active');
            });
        });

        // Активируем нужную вкладку при загрузке
        const activeTabElement = document.querySelector(`.nav-link[href="${activeTab}"]`);
        if (activeTabElement) {
            activeTabElement.classList.add('active');
            document.querySelector(activeTabElement.getAttribute('href')).classList.add('show', 'active');
        }
    });
</script>

{% endblock %}

templates/article_card.html
<div class="card border-0 shadow">
    {% if image is none %}
      <img src="{{ url_for('static', filename='img/no_image.jpg') }}" class="card-img-top" alt="Заглушка изображения">
    {% else %}
    <img src="data:image/png;base64,{{ image|safe }}" class="card-img-top" alt="{{ article.article_title }}">
    {% endif %}
    <div class="card-body text-center">
        <h5 class="card-title"> {{ article.article_title }}</h5>
        <p class="card-text"> Статья {{ (page - 1)*3 + index }} в курсе {{ course.course_title }}</p>
        <a href="{{ url_for('courses.show_article_page', course_id=course.course_id, article_id=article.article_id, active_tab='#article') }}"
           class="btn btn-primary">Перейти</a>
    </div>
</div>

templates/fav_course_card.html
<div class="col">
    <a href="{{ url_for('courses.show_course_page', course_id=course.course_id) }}" class="text-decoration-none text-dark">
        <div class="card shadow-sm">
            <svg
                class="bd-placeholder-img card-img-top"
                width="100%" height="225"
                xmlns="http://www.w3.org/2000/svg"
                role="img"
                aria-label="Placeholder: Thumbnail"
                preserveAspectRatio="xMidYMid slice"
                focusable="false">
                <title>Placeholder</title>
                <rect width="100%" height="100%" fill="#55595c"/>
                <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ course.course_title }}</text>
            </svg>
            <div class="card-body">
                <p class="card-text">{{ course.description }}</p>
                <div class="d-flex justify-content-between align-items-center">
                   <div class="ms-auto btn-group">
                        <a href="{{ url_for('courses.unfavourite_course_from_profile', course_id=course.course_id) }}" class="btn btn-sm btn-outline-secondary" role="button">
                        <i class="bi bi-bookmarks-fill"></i></a>
                       {% if course.author == current_user or current_user.role == 'admin' %}
                    <a href="{{ url_for('courses.edit_course', course_id=course.course_id) }}" class="btn btn-sm btn-outline-secondary" role="button">
                        <i class="bi bi-pencil"></i></a>
                    <a href="{{ url_for('courses.delete_course', course_id=course.course_id) }}" class="btn btn-sm btn-outline-secondary" role="button">
                        <i class="bi bi-trash"></i></a>
                       {% endif %}
                </div>
                </div>
            </div>
        </div>
    </a>
</div>